[licenses]
copyleft = "allow"
allow-osi-fsf-free = "both"
# Explicitly allowing certain licenses is neccessary because SPDX incorrectly
# neglects to mark certain licenses as FSF/OSI approved when they really are.
allow = ["BSD-2-Clause"]
# Denying common free-but-incompatible-with-the-GPL licenses.
deny = [
    "AFL-1.1",
    "AFL-1.2",
    "AFL-2.0",
    "AFL-2.1",
    "AFL-3.0",
    "AGPL-1.0-only",
    "Apache-1.0",
    "Apache-1.1",
    "APSL-1.0",
    "APSL-1.1",
    "APSL-1.2",
    "APSL-2.0",
    "BSD-4-Clause",
    "CDDL-1.0",
    "CDDL-1.1",
    "CPL-1.0",
    "EPL-1.0",
    "EPL-2.0",
    "EUPL-1.0",
    "EUPL-1.1",
    "EUPL-1.2",
    "IPL-1.0",
    "LPPL-1.0",
    "LPPL-1.1",
    "LPPL-1.2",
    "LPPL-1.3a",
    "LPPL-1.3c",
    "MS-PL",
    "MS-RL",
    "Nokia",
    "OpenSSL",
    "OSL-1.0",
    "OSL-1.1",
    "OSL-2.0",
    "OSL-2.1",
    "OSL-3.0",
    "Python-2.0",
    "QPL-1.0",
    "SISSL",
    "SISSL-1.2",
    "Zend-2.0",
    "ZPL-1.1",
    "ZPL-2.0",
    "ZPL-2.1",
]
